version: "3.9"

services:
    app:
        build:
            context: docker/php
            dockerfile: Dockerfile
        container_name: darkdiabet_app
        depends_on:
            -   db
        working_dir: /var/www/html
        volumes:
            -   .:/var/www/html
            -  ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    server:
        image: nginx:stable
        ports:
            -   "8081:80"
        restart: unless-stopped
        container_name: darkdiabet_server
        volumes:
            -   .:/var/www/html
            -   ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    db:
        image: postgres:alpine
        ports:
            - "15432:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        container_name: darkdiabet_db
        volumes:
            -   ./db/data:/var/lib/postgresql/data
    rabbitmq:
        image: rabbitmq:3.11.9-management
        ports:
            - 15672:15672
        container_name: darkdiabet_rabbit


